-- MySQL Script generated by MySQL Workbench
-- lun 18 mar 2024 17:55:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mimuebleriadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mimuebleriadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mimuebleriadb` ;
USE `mimuebleriadb` ;

-- -----------------------------------------------------
-- Table `mimuebleriadb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`Usuario` (
    `idUsuario` INT NOT NULL AUTO_INCREMENT,
    `rol` ENUM('ADMIN', 'FACTORY', 'SALES') NOT NULL,
    `nombre` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NOT NULL,
    `user` VARCHAR(45) NOT NULL,
    `password` VARCHAR(45) NOT NULL,
    `estado` TINYINT(1) NULL DEFAULT 1,
    PRIMARY KEY (`idUsuario`),
    UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimuebleriadb`.`Pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`Pieza` (
    `idPieza` INT NOT NULL,
    `nombre` VARCHAR(45) NULL,
    `precioUnidad` DOUBLE NOT NULL,
    `existencias` INT NOT NULL,
    `minimoExitencias` INT NOT NULL,
    PRIMARY KEY (`idPieza`),
    UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimuebleriadb`.`Ensamble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`Ensamble` (
    `idManualEnsamble` INT NOT NULL,
    `nombre` VARCHAR(45) NOT NULL,
    `instrucciones` VARCHAR(1000) NOT NULL,
    `descripcion` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`idManualEnsamble`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimuebleriadb`.`DetalleEnsamble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`DetalleEnsamble` (
    `idDetalleEnsamble` INT NOT NULL,
    `idManualEnsamble` INT NOT NULL,
    `idPieza` INT NOT NULL,
    `cantidad` INT NOT NULL,
    PRIMARY KEY (`idDetalleEnsamble`),
    INDEX `fk_DetalleEnsamble_1_idx` (`idManualEnsamble` ASC) VISIBLE,
    INDEX `fk_DetalleEnsamble_2_idx` (`idPieza` ASC) VISIBLE,
    CONSTRAINT `fk_DetalleEnsamble_1`
    FOREIGN KEY (`idManualEnsamble`)
    REFERENCES `mimuebleriadb`.`Ensamble` (`idManualEnsamble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_DetalleEnsamble_2`
    FOREIGN KEY (`idPieza`)
    REFERENCES `mimuebleriadb`.`Pieza` (`idPieza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimuebleriadb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`Cliente` (
 `nit` INT NOT NULL,
 `nombre` VARCHAR(45) NOT NULL,
    `telefono` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`nit`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimuebleriadb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`Factura` (
     `idFactura` INT NOT NULL,
     `nit` INT NOT NULL,
     `idUsuarioVendedor` INT NOT NULL,
     `fecha` DATE NOT NULL,
     PRIMARY KEY (`idFactura`),
    INDEX `fk_Factura_1_idx` (`idUsuarioVendedor` ASC, `nit` ASC) VISIBLE,
    CONSTRAINT `fk_Factura_1`
    FOREIGN KEY (`idUsuarioVendedor`)
    REFERENCES `mimuebleriadb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Factura_2`
    FOREIGN KEY (nit)
    REFERENCES `mimuebleriadb`.`Cliente` (nit)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimuebleriadb`.`Mueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`Mueble` (
    `idMueble` INT NOT NULL,
    `idUsuarioEnsamble` INT NOT NULL,
    `fechaEsamble` DATE NOT NULL,
    `precioVenta` DOUBLE NOT NULL,
    `costoEnsamble` DOUBLE NOT NULL,
    `estado` TINYINT(1) NULL DEFAULT 0,
    PRIMARY KEY (`idMueble`),
    CONSTRAINT `fk_MuebleRegistro_2`
    FOREIGN KEY (`idUsuarioEnsamble`)
    REFERENCES `mimuebleriadb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimuebleriadb`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`DetalleFactura` (
    `idDetalleFactura` INT NOT NULL,
    `idFactura` INT NOT NULL,
    `idMueble` INT NOT NULL,
    PRIMARY KEY (`idDetalleFactura`),
    INDEX `fk_DetalleFactura_1_idx` (`idMueble` ASC) VISIBLE,
    INDEX `fk_DetalleFactura_2_idx` (`idFactura` ASC) VISIBLE,
    CONSTRAINT `fk_DetalleFactura_1`
    FOREIGN KEY (`idMueble`)
    REFERENCES `mimuebleriadb`.`Mueble` (`idMueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_DetalleFactura_2`
    FOREIGN KEY (`idFactura`)
    REFERENCES `mimuebleriadb`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimuebleriadb`.`Devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`Devolucion` (
                                                            `idDevolucion` INT NOT NULL,
                                                            `idDetalleFactura` INT NOT NULL,
                                                            `descripcion` VARCHAR(45) NOT NULL,
    `fecha` DATE NOT NULL,
    `idUsuario` INT NOT NULL,
    `perdida` DOUBLE NULL,
    PRIMARY KEY (`idDevolucion`),
    INDEX `fk_Devolucion_1_idx` (`idDetalleFactura` ASC) VISIBLE,
    INDEX `fk_Devolucion_2_idx` (`idUsuario` ASC) VISIBLE,
    CONSTRAINT `fk_Devolucion_1`
    FOREIGN KEY (`idDetalleFactura`)
    REFERENCES `mimuebleriadb`.`DetalleFactura` (`idDetalleFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Devolucion_2`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mimuebleriadb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimuebleriadb`.`InventarioPieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`InventarioPieza` (
                                                                 `idInventarioPieza` INT NOT NULL,
                                                                 `idPieza` INT NOT NULL,
                                                                 `costo` DOUBLE NOT NULL,
                                                                 `cantidad` INT NOT NULL,
                                                                 PRIMARY KEY (`idInventarioPieza`),
    INDEX `fk_InventarioPieza_1_idx` (`idPieza` ASC) VISIBLE,
    CONSTRAINT `fk_InventarioPieza_1`
    FOREIGN KEY (`idPieza`)
    REFERENCES `mimuebleriadb`.`Pieza` (`idPieza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimuebleriadb`.`DetalleMueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimuebleriadb`.`DetalleMueble` (
                                                               `idDetalleMueble` INT NOT NULL,
                                                               `idMueble` INT NOT NULL,
                                                               `idPieza` INT NOT NULL,
                                                               `cantidad` INT NOT NULL,
                                                               PRIMARY KEY (`idDetalleMueble`),
    INDEX `fk_DetalleMueble_1_idx` (`idMueble` ASC) VISIBLE,
    INDEX `fk_DetalleMueble_2_idx` (`idPieza` ASC) VISIBLE,
    CONSTRAINT `fk_DetalleMueble_1`
    FOREIGN KEY (`idMueble`)
    REFERENCES `mimuebleriadb`.`Mueble` (`idMueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_DetalleMueble_2`
    FOREIGN KEY (`idPieza`)
    REFERENCES `mimuebleriadb`.`Pieza` (`idPieza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
