ALTER TABLE Piece MODIFY COLUMN pieceId BIGINT AUTO_INCREMENT;
ALTER TABLE Assembly MODIFY COLUMN assemblyId BIGINT AUTO_INCREMENT;
ALTER TABLE AssemblyDetail MODIFY COLUMN assemblyDetailId BIGINT AUTO_INCREMENT;
ALTER TABLE Furniture MODIFY COLUMN furnitureId BIGINT AUTO_INCREMENT;
ALTER TABLE InvoiceDetail MODIFY COLUMN invoiceDetailId BIGINT AUTO_INCREMENT;
ALTER TABLE Refund MODIFY COLUMN refundId BIGINT AUTO_INCREMENT;
ALTER TABLE PieceInventory MODIFY COLUMN pieceInventoryId BIGINT AUTO_INCREMENT;
ALTER TABLE FurnitureDetail MODIFY COLUMN furnitureDetailId BIGINT AUTO_INCREMENT;
